"use client";

import React, { useState } from "react";
import { InlineWidget, PopupButton } from "react-calendly";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Booking",
  //   description: "Generated by create next app",
};

const Template = () => {
  const [loading, setLoading] = useState(true);

  return (
    <main className="booking-page">
      <section className="!pt-[15.5rem] sm:!pt-[24.5rem] !pb-[15rem] sm:!pb-[15rem]">
        <div className="container">
          <h6 className="subtitle text-center sm:!mb-[5.2rem]">book a fitting</h6>
          <h1 className="display-2 text-center leading-[1.1] mb-[1.7rem] sm:mb-[3rem]">
            Book your
            <br />
            Bespoke Fitting
          </h1>
          <div className="text-secondary-800 text-sm sm:text-[1.125rem] max-w-[300px] text-center mx-auto mb-[2rem] leading-[1.65]">
            Begin your tailoring journey with Lawrence & Winslade
          </div>
          <div className=" h-[900px]  md:h-[900px] xl:h-[700px] relative">
            <InlineWidget
              url="https://calendly.com/karendev99test/30min"
              className="relative z-2"
              styles={{ width: "100%", height: "100%", minHeight: "500px" }}
              // pageSettings={{ hideLandingPageDetails: true }}
              // prefill={{}}
            />
            {/* {loading && (
            <div className="absolute top-[50%] z-1 left-[50%] transform-[translate(-50%,-50%)] flex justify-center items-center bg-white">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-gray-900"></div>
            </div>
          )} */}
          </div>
        </div>
      </section>
    </main>
  );
};

export default Template;
