"use client";

import React, { useState } from "react";
import { InlineWidget, PopupButton } from "react-calendly";
import type { Metadata } from "next";
import { Navbar } from "@/components/index";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Booking",
  //   description: "Generated by create next app",
};

const Template = () => {
  return (
    <main className="booking-page">
      <header className="hero">
        <Navbar>
          <div className="breadcrumbs  border-y border-line py-4 sm:py-5">
            <div className="container flex items-center gap-2">
              <Link href="/" className="link text-xs font-medium px-1 underline">
                Home
              </Link>
              <div className="dot w-1 h-1 rounded-full bg-dark"></div>
              <div className="link text-xs font-medium px-1 pointer-events-none text-secondary-500">Booking</div>
            </div>
          </div>
        </Navbar>
      </header>
      <section className=" !pb-[1rem] sm:!pb-[6rem] sm:!pt-[6rem] lg:!pt-[5rem] 4xl:!pt-[13rem]">
        <div className="container">
          <h6 className="subtitle text-center sm:!mb-[5.2rem]">book a fitting</h6>
          <h1 className="display-2 text-center leading-[1.1] mb-[1.7rem] sm:mb-[3rem]">
            Book your
            <br />
            Bespoke Fitting
          </h1>
          <div className="text-secondary-800 text-sm sm:text-[1.125rem] max-w-[300px] text-center mx-auto mb-[2rem] leading-[1.65]">
            Begin your tailoring journey with Lawrence & Winslade
          </div>
    
        </div>
      </section>
      
    </main>
  );
};

export default Template;
