"use client";

import React, { useState } from "react";
import type { Metadata } from "next";
import Image from "next/image";
import localData from "@/localData";
import { ButtonDemo, Navbar } from "@/components/index";
import Link from "next/link";

const { fabricsCoverImage } = localData.images;

export const metadata: Metadata = {
  title: "Booking",
  //   description: "Generated by create next app",
};

const Template = () => {
  return (
    <main className="fabrics-page">
      <header className="hero  sm:min-h-[100vh] flex flex-col">
        <Navbar>
          <div className="breadcrumbs  border-y border-line py-4 sm:py-5">
            <div className="container flex items-center gap-2">
              <Link href="/" className="link text-xs font-medium px-1 underline">
                Home
              </Link>
              <div className="dot w-1 h-1 rounded-full bg-dark"></div>
              <div className="link text-xs font-medium px-1 pointer-events-none text-secondary-500">Our Fabrics</div>
            </div>
          </div>
        </Navbar>
        <ShowcaseSection />
      </header>
    </main>
  );
};

const ShowcaseSection = () => {
  return (
    <div className=" flex-1  pb-[2rem]  flex flex-col items-center  ">
      <div className={`flex flex-1 border hero-center  bg-cover w-full relative  py-[8rem] sm:py-[4rem] 4xl:py-[8rem]  `}>
        <Image
          src={fabricsCoverImage}
          // width={1920}
          // height={720}
          fill={true}
          alt="background image"
          className="absolute top-0 left-0 w-full h-full object-cover "
        />
        <div className="overlay absolute bg-[rgba(0,0,0,0.3)] sm:hidden top-0 left-0 w-full h-full"></div>
        <div className="container flex-1   relative flex gap-10 flex-col lg:flex-row items-center  justify-center ">
          <div className="showcase-content text-white text-center ">
            <div className="text-[0.625rem] sm:text-sm uppercase mb-[2rem]">our partners</div>
            <h1 className="text-[2.188rem] leading-[1.2] sm:text-4xl max-w-[400px] sm:max-w-[500px]">
             Discover the world’s finest fabrics
            </h1>
          </div>
       
        </div>
      </div>
    </div>
  );
};

export default Template;
