import React from "react";
import Template from "./Template";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pricing",
  //   description: "Generated by create next app",
};

const page = () => {
  return <Template />;
};

export default page;
